// <auto-generated />
using System;
using F1Manager.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Manager.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529151626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("F1Manager.Web.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Corrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeGrandePremio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Corridas");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Equipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FabricanteMotor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipas");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroCarro")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("F1Manager.Web.Models.ResultadoCorrida", b =>
                {
                    b.Property<int>("PilotoId")
                        .HasColumnType("int");

                    b.Property<int>("CorridaId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoFinal")
                        .HasColumnType("int");

                    b.Property<string>("TempoVoltaRapida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PilotoId", "CorridaId");

                    b.HasIndex("CorridaId");

                    b.ToTable("ResultadosCorridas");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Corrida", b =>
                {
                    b.HasOne("F1Manager.Web.Models.Campeonato", "Campeonato")
                        .WithMany("Corridas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Piloto", b =>
                {
                    b.HasOne("F1Manager.Web.Models.Equipa", "Equipa")
                        .WithMany("Pilotos")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipa");
                });

            modelBuilder.Entity("F1Manager.Web.Models.ResultadoCorrida", b =>
                {
                    b.HasOne("F1Manager.Web.Models.Corrida", "Corrida")
                        .WithMany("Resultados")
                        .HasForeignKey("CorridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Manager.Web.Models.Piloto", "Piloto")
                        .WithMany("Resultados")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corrida");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Campeonato", b =>
                {
                    b.Navigation("Corridas");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Corrida", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Equipa", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("F1Manager.Web.Models.Piloto", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
